"""empty message

Revision ID: 375c04d191d8
Revises: 735bdb4b02a8
Create Date: 2021-06-11 20:49:13.960112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '375c04d191d8'
down_revision = '735bdb4b02a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('address', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'address')
    # ### end Alembic commands ###
