"""empty message

Revision ID: 55e99c446877
Revises: a2f3160e2240
Create Date: 2021-06-11 20:06:49.356394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55e99c446877'
down_revision = 'a2f3160e2240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('Genres', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'Genres')
    # ### end Alembic commands ###
